"""migracion modelos

Revision ID: caffc59ac194
Revises: 
Create Date: 2025-07-21 12:31:08.302452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caffc59ac194'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maquinaria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('serie', sa.String(length=50), nullable=False),
    sa.Column('ubicacion', sa.String(length=50), nullable=False),
    sa.Column('fecha_adquisicion', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mantenimiento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('maquinaria_id', sa.UUID(), nullable=False),
    sa.Column('tipo_mantenimiento', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('responsable', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['maquinaria_id'], ['maquinaria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materiales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_material', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('unidad_medida', sa.String(length=50), nullable=False),
    sa.Column('vida_util', sa.Numeric(), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(), nullable=False),
    sa.Column('stock_actual', sa.Numeric(), nullable=False),
    sa.Column('stock_maximo', sa.Numeric(), nullable=False),
    sa.Column('proveedor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_horas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('maquinaria_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('horas_maquina', sa.Numeric(), nullable=False),
    sa.Column('actividad', sa.String(length=50), nullable=False),
    sa.Column('operador', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['maquinaria_id'], ['maquinaria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instalacion_material',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('materiales_id', sa.UUID(), nullable=False),
    sa.Column('maquinaria_id', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Numeric(), nullable=False),
    sa.Column('fecha_instalacion', sa.Date(), nullable=False),
    sa.Column('horas_maquina', sa.Numeric(), nullable=False),
    sa.Column('responsable', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['maquinaria_id'], ['maquinaria.id'], ),
    sa.ForeignKeyConstraint(['materiales_id'], ['materiales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instalacion_material')
    op.drop_table('registro_horas')
    op.drop_table('materiales')
    op.drop_table('mantenimiento')
    op.drop_table('proveedores')
    op.drop_table('maquinaria')
    # ### end Alembic commands ###
